### ISSUE TITLE
Node 12 Checklist

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1500]
Node v12 is now LTS, while we are not in a rush to use this, I thought it would be good to have a list of things need to done or are pending.

- [x] Update [node-rdkafka](https://github.com/Blizzard/node-rdkafka) to a version that is compatible with node 12/10/8 (it is on master but unreleased).
- [x] Make sure all of the other dependencies compile and work right
- [x] Update our CI tests to run node 12 (and node 10)
- [x] Update our asset bundles to test/build in node 12 (and node 10)
- [x] Use it for local development for a few weeks (to make sure it works well locally)
- [ ] Create a rc docker image with node 12 and run it through QA
- [ ] Create an official release using node 12

**Comment by peterdemartini** [comment]
Asset bundle versions that support node 12:

- [elasticsearch-assets@v1.6.2](https://github.com/terascope/elasticsearch-assets/releases/v1.6.2)
- [kafka-assets@v2.4.2](https://github.com/terascope/kafka-assets/releases/v2.4.2)
- [file-assets@v0.8.3](https://github.com/terascope/file-assets/releases/v0.8.3)
- [standard-assets@v0.3.1](https://github.com/terascope/standard-assets/releases/v0.3.1)
- [hdfs-assets@v0.3.1](https://github.com/terascope/hdfs-assets/releases/v0.3.1)
